local ADDON_NAME, ns = ...

-- Pet ability ranks for Classic Era: every rank a hunter pet can learn,
-- with training point cost, required pet level, usable families and the
-- learning source. Spell IDs / rank order / TP costs from the 1.15 client
-- DB (SkillLineAbility), obtainability and sources from Petopia Classic.
-- Display names/icons come from GetSpellInfo(spellId) at runtime.
--
-- ability(key, families): families = CreatureFamily IDs (nil = all).
-- rank(spellId, rank, petLevel, tpCost, source, moneyCost): source "t" =
-- pet trainer, "w" = taming wild beasts, "tw" = both, "n" = no known
-- source. moneyCost in copper (cmangos 1.12 npc_trainer; 0 for taming).

local ability, rank = ns.NewPetAbilityDB()

-- DATA_START (generated by Generate-PetTipsData.ps1; do not hand-edit)
ability("arcaneresistance", nil) -- Arcane Resistance: all families
rank(24493, 1, 20, 5, "t", 440) -- Arcane Resistance 1
rank(24497, 2, 30, 15, "t", 1440) -- Arcane Resistance 2
rank(24500, 3, 40, 45, "t", 3240) -- Arcane Resistance 3
rank(24501, 4, 50, 90, "t", 6480) -- Arcane Resistance 4
ability("bite", { 1, 2, 3, 4, 5, 6, 7, 9, 11, 12, 21, 24, 25, 27 }) -- Bite: Wolf, Cat, Spider, Bear, Boar, Crocolisk, Carrion Bird, Gorilla, Raptor, Tallstrider, Turtle, Bat, Hyena, Wind Serpent
rank(17253, 1, 1, 1, "w", 0) -- Bite 1
rank(17255, 2, 8, 4, "w", 0) -- Bite 2
rank(17256, 3, 16, 7, "w", 0) -- Bite 3
rank(17257, 4, 24, 10, "w", 0) -- Bite 4
rank(17258, 5, 32, 13, "w", 0) -- Bite 5
rank(17259, 6, 40, 17, "w", 0) -- Bite 6
rank(17260, 7, 48, 21, "w", 0) -- Bite 7
rank(17261, 8, 56, 25, "w", 0) -- Bite 8
ability("charge", { 5 }) -- Charge: Boar
rank(7371, 1, 1, 5, "w", 0) -- Charge 1
rank(26177, 2, 12, 9, "w", 0) -- Charge 2
rank(26178, 3, 24, 13, "w", 0) -- Charge 3
rank(26179, 4, 36, 17, "n", 0) -- Charge 4
rank(26201, 5, 48, 21, "w", 0) -- Charge 5
rank(27685, 6, 60, 25, "w", 0) -- Charge 6
ability("claw", { 2, 4, 7, 8, 11, 20, 26 }) -- Claw: Cat, Bear, Carrion Bird, Crab, Raptor, Scorpid, Owl
rank(16827, 1, 1, 1, "w", 0) -- Claw 1
rank(16828, 2, 8, 4, "w", 0) -- Claw 2
rank(16829, 3, 16, 7, "w", 0) -- Claw 3
rank(16830, 4, 24, 10, "w", 0) -- Claw 4
rank(16831, 5, 32, 13, "w", 0) -- Claw 5
rank(16832, 6, 40, 17, "w", 0) -- Claw 6
rank(3010, 7, 48, 21, "w", 0) -- Claw 7
rank(3009, 8, 56, 25, "w", 0) -- Claw 8
ability("cower", nil) -- Cower: all families
rank(1742, 1, 5, 8, "w", 0) -- Cower 1
rank(1753, 2, 15, 10, "w", 0) -- Cower 2
rank(1754, 3, 25, 12, "w", 0) -- Cower 3
rank(1755, 4, 35, 14, "w", 0) -- Cower 4
rank(1756, 5, 45, 16, "w", 0) -- Cower 5
rank(16697, 6, 55, 18, "w", 0) -- Cower 6
ability("dash", { 1, 2, 5, 12, 25 }) -- Dash: Wolf, Cat, Boar, Tallstrider, Hyena
rank(23099, 1, 30, 15, "w", 0) -- Dash 1
rank(23109, 2, 40, 20, "w", 0) -- Dash 2
rank(23110, 3, 50, 25, "w", 0) -- Dash 3
ability("dive", { 7, 24, 26, 27 }) -- Dive: Carrion Bird, Bat, Owl, Wind Serpent
rank(23145, 1, 30, 15, "w", 0) -- Dive 1
rank(23147, 2, 40, 20, "w", 0) -- Dive 2
rank(23148, 3, 50, 25, "w", 0) -- Dive 3
ability("fireresistance", nil) -- Fire Resistance: all families
rank(23992, 1, 20, 5, "t", 440) -- Fire Resistance 1
rank(24439, 2, 30, 15, "t", 1440) -- Fire Resistance 2
rank(24444, 3, 40, 45, "t", 3240) -- Fire Resistance 3
rank(24445, 4, 50, 90, "t", 6480) -- Fire Resistance 4
ability("frostresistance", nil) -- Frost Resistance: all families
rank(24446, 1, 20, 5, "t", 440) -- Frost Resistance 1
rank(24447, 2, 30, 15, "t", 1440) -- Frost Resistance 2
rank(24448, 3, 40, 45, "t", 3240) -- Frost Resistance 3
rank(24449, 4, 50, 90, "t", 6480) -- Frost Resistance 4
ability("furioushowl", { 1 }) -- Furious Howl: Wolf
rank(24604, 1, 10, 10, "w", 0) -- Furious Howl 1
rank(24605, 2, 24, 15, "w", 0) -- Furious Howl 2
rank(24603, 3, 40, 20, "w", 0) -- Furious Howl 3
rank(24597, 4, 56, 25, "w", 0) -- Furious Howl 4
ability("greatstamina", nil) -- Great Stamina: all families
rank(4187, 1, 10, 5, "t", 10) -- Great Stamina 1
rank(4188, 2, 12, 10, "t", 120) -- Great Stamina 2
rank(4189, 3, 18, 15, "t", 400) -- Great Stamina 3
rank(4190, 4, 24, 25, "t", 1260) -- Great Stamina 4
rank(4191, 5, 30, 50, "t", 1440) -- Great Stamina 5
rank(4192, 6, 36, 75, "t", 2520) -- Great Stamina 6
rank(4193, 7, 42, 100, "t", 4320) -- Great Stamina 7
rank(4194, 8, 48, 125, "t", 5760) -- Great Stamina 8
rank(5041, 9, 54, 150, "t", 7560) -- Great Stamina 9
rank(5042, 10, 60, 185, "t", 9000) -- Great Stamina 10
ability("growl", nil) -- Growl: all families
rank(2649, 1, 1, 0, "t", 1) -- Growl 1
rank(14916, 2, 10, 0, "t", 1) -- Growl 2
rank(14917, 3, 20, 0, "t", 440) -- Growl 3
rank(14918, 4, 30, 0, "t", 1440) -- Growl 4
rank(14919, 5, 40, 0, "t", 3240) -- Growl 5
rank(14920, 6, 50, 0, "t", 6480) -- Growl 6
rank(14921, 7, 60, 0, "t", 9000) -- Growl 7
ability("lightningbreath", { 27 }) -- Lightning Breath: Wind Serpent
rank(24844, 1, 1, 1, "n", 0) -- Lightning Breath 1
rank(25008, 2, 12, 5, "w", 0) -- Lightning Breath 2
rank(25009, 3, 24, 10, "w", 0) -- Lightning Breath 3
rank(25010, 4, 36, 15, "w", 0) -- Lightning Breath 4
rank(25011, 5, 48, 20, "w", 0) -- Lightning Breath 5
rank(25012, 6, 60, 25, "w", 0) -- Lightning Breath 6
ability("naturalarmor", nil) -- Natural Armor: all families
rank(24545, 1, 10, 1, "t", 10) -- Natural Armor 1
rank(24549, 2, 12, 5, "t", 120) -- Natural Armor 2
rank(24550, 3, 18, 10, "t", 400) -- Natural Armor 3
rank(24551, 4, 24, 15, "t", 1260) -- Natural Armor 4
rank(24552, 5, 30, 25, "t", 1440) -- Natural Armor 5
rank(24553, 6, 36, 50, "t", 2520) -- Natural Armor 6
rank(24554, 7, 42, 75, "t", 4320) -- Natural Armor 7
rank(24555, 8, 48, 100, "t", 5760) -- Natural Armor 8
rank(24629, 9, 54, 125, "t", 7560) -- Natural Armor 9
rank(24630, 10, 60, 150, "t", 9000) -- Natural Armor 10
ability("natureresistance", nil) -- Nature Resistance: all families
rank(24492, 1, 20, 5, "t", 440) -- Nature Resistance 1
rank(24502, 2, 30, 15, "t", 1440) -- Nature Resistance 2
rank(24503, 3, 40, 45, "t", 3240) -- Nature Resistance 3
rank(24504, 4, 50, 90, "t", 6480) -- Nature Resistance 4
ability("prowl", { 2 }) -- Prowl: Cat
rank(24450, 1, 30, 15, "w", 0) -- Prowl 1
rank(24452, 2, 40, 20, "w", 0) -- Prowl 2
rank(24453, 3, 50, 25, "w", 0) -- Prowl 3
ability("scorpidpoison", { 20 }) -- Scorpid Poison: Scorpid
rank(24640, 1, 8, 10, "w", 0) -- Scorpid Poison 1
rank(24583, 2, 24, 15, "w", 0) -- Scorpid Poison 2
rank(24586, 3, 40, 20, "w", 0) -- Scorpid Poison 3
rank(24587, 4, 56, 25, "w", 0) -- Scorpid Poison 4
ability("screech", { 7, 24, 26 }) -- Screech: Carrion Bird, Bat, Owl
rank(24423, 1, 8, 10, "w", 0) -- Screech 1
rank(24577, 2, 24, 15, "w", 0) -- Screech 2
rank(24578, 3, 48, 20, "w", 0) -- Screech 3
rank(24579, 4, 56, 25, "w", 0) -- Screech 4
ability("shadowresistance", nil) -- Shadow Resistance: all families
rank(24488, 1, 20, 5, "t", 40) -- Shadow Resistance 1
rank(24505, 2, 30, 15, "t", 1440) -- Shadow Resistance 2
rank(24506, 3, 40, 45, "t", 3240) -- Shadow Resistance 3
rank(24507, 4, 50, 90, "t", 6480) -- Shadow Resistance 4
ability("shellshield", { 21 }) -- Shell Shield: Turtle
rank(26064, 1, 20, 15, "w", 0) -- Shell Shield 1
ability("thunderstomp", { 9 }) -- Thunderstomp: Gorilla
rank(26090, 1, 30, 15, "w", 0) -- Thunderstomp 1
rank(26187, 2, 40, 20, "w", 0) -- Thunderstomp 2
rank(26188, 3, 50, 25, "w", 0) -- Thunderstomp 3
-- DATA_END
