local ADDON_NAME, ns = ...

-- Tameable beasts that teach at least one pet ability rank (learned by
-- taming them and letting them use the ability). npc IDs match the
-- creature GUID npc field; mob names are English (Petopia has no
-- translations - shown as-is on all locales). Zone names are shown
-- localized at runtime, resolved from zoneIds: positive = uiMapID
-- (C_Map.GetMapInfo), negative = -instanceMapID (GetRealZoneText /
-- matched against GetInstanceInfo). The English zone string is kept
-- only as a fallback if an ID fails to resolve.
--
-- mob(npcId, name, familyId, minLevel, maxLevel, zone, { zoneIds }, { spellIds })

local mob = ns.NewTameMobDB()

-- DATA_START (generated by Generate-PetTipsData.ps1; do not hand-edit)
mob(30, "Forest Spider", 3, 5, 6, "Elwynn Forest", { 1429 }, { 17253 }) -- Spider
mob(113, "Stonetusk Boar", 5, 7, 8, "Elwynn Forest", { 1429 }, { 7371 }) -- Boar
mob(118, "Prowler", 1, 9, 10, "Elwynn Forest", { 1429 }, { 17255 }) -- Wolf
mob(119, "Longsnout", 5, 10, 11, "Elwynn Forest", { 1429 }, { 7371 }) -- Boar
mob(154, "Greater Fleshripper", 7, 16, 17, "Westfall", { 1436 }, { 24423 }) -- Carrion Bird
mob(157, "Goretusk", 5, 14, 15, "Westfall", { 1436 }, { 26177 }) -- Boar
mob(330, "Princess", 5, 9, 9, "Elwynn Forest", { 1429 }, { 7371 }) -- Boar
mob(345, "Bellygrub", 5, 24, 24, "Redridge Mountains", { 1433 }, { 26178 }) -- Boar
mob(390, "Porcine Entourage", 5, 7, 7, "Elwynn Forest", { 1429 }, { 7371 }) -- Boar
mob(442, "Tarantula", 3, 15, 16, "Redridge Mountains", { 1433 }, { 17255 }) -- Spider
mob(454, "Young Goretusk", 5, 12, 13, "Westfall", { 1436 }, { 26177 }) -- Boar
mob(505, "Greater Tarantula", 3, 19, 20, "Redridge Mountains", { 1433 }, { 17256 }) -- Spider
mob(521, "Lupos", 1, 23, 23, "Duskwood", { 1431 }, { 17256 }) -- Wolf
mob(524, "Rockhide Boar", 5, 7, 8, "Elwynn Forest", { 1429 }, { 7371 }) -- Boar
mob(547, "Great Goretusk", 5, 16, 17, "Redridge Mountains; Westfall", { 1433, 1436 }, { 26177 }) -- Boar
mob(569, "Green Recluse", 3, 21, 22, "Duskwood", { 1431 }, { 17256 }) -- Spider
mob(574, "Naraxis", 3, 27, 27, "Duskwood", { 1431 }, { 17257 }) -- Spider
mob(616, "Chatter", 3, 23, 23, "Redridge Mountains", { 1433 }, { 17256 }) -- Spider
mob(628, "Black Ravager", 1, 24, 25, "Duskwood", { 1431 }, { 17257 }) -- Wolf
mob(681, "Young Stranglethorn Tiger", 2, 30, 31, "Stranglethorn Vale", { 1434 }, { 1754 }) -- Cat
mob(682, "Stranglethorn Tiger", 2, 32, 33, "Stranglethorn Vale", { 1434 }, { 23099 }) -- Cat
mob(683, "Young Panther", 2, 30, 31, "Stranglethorn Vale", { 1434 }, { 1754 }) -- Cat
mob(684, "Shadowmaw Panther", 2, 37, 38, "Stranglethorn Vale", { 1434 }, { 24450 }) -- Cat
mob(708, "Small Crag Boar", 5, 3, 3, "Dun Morogh", { 1426 }, { 7371 }) -- Boar
mob(728, "Bhag'thera", 2, 40, 40, "Stranglethorn Vale", { 1434 }, { 23109 }) -- Cat
mob(729, "Sin'Dall", 2, 37, 37, "Stranglethorn Vale", { 1434 }, { 23099 }) -- Cat
mob(731, "King Bangalash", 2, 43, 43, "Stranglethorn Vale", { 1434 }, { 16832, 23109 }) -- Cat
mob(736, "Panther", 2, 32, 33, "Stranglethorn Vale", { 1434 }, { 1754 }) -- Cat
mob(767, "Swamp Jaguar", 2, 36, 37, "Swamp of Sorrows", { 1435 }, { 23099 }) -- Cat
mob(768, "Shadow Panther", 2, 39, 40, "Swamp of Sorrows", { 1435 }, { 24450 }) -- Cat
mob(769, "Deathstrike Tarantula", 3, 40, 41, "Swamp of Sorrows", { 1435 }, { 17259 }) -- Spider
mob(822, "Young Forest Bear", 4, 8, 9, "Elwynn Forest", { 1429 }, { 16828 }) -- Bear
mob(833, "Coyote Packleader", 1, 11, 12, "Westfall", { 1436 }, { 17255, 24604 }) -- Wolf
mob(834, "Coyote", 1, 10, 11, "Westfall", { 1436 }, { 17255 }) -- Wolf
mob(922, "Silt Crawler", 8, 40, 41, "Swamp of Sorrows", { 1435 }, { 16832 }) -- Crab
mob(976, "Kurzen War Tiger", 2, 32, 33, "Stranglethorn Vale", { 1434 }, { 23099 }) -- Cat
mob(1087, "Sawtooth Snapper", 6, 41, 42, "Swamp of Sorrows", { 1435 }, { 17259 }) -- Crocolisk
mob(1088, "Monstrous Crawler", 8, 43, 44, "Swamp of Sorrows", { 1435 }, { 16832 }) -- Crab
mob(1108, "Mistvale Gorilla", 9, 32, 33, "Stranglethorn Vale", { 1434 }, { 26090 }) -- Gorilla
mob(1112, "Leech Widow", 3, 24, 24, "Wetlands", { 1437 }, { 17257 }) -- Spider
mob(1114, "Jungle Thunderer", 9, 37, 38, "Stranglethorn Vale", { 1434 }, { 26090 }) -- Gorilla
mob(1125, "Crag Boar", 5, 5, 6, "Dun Morogh", { 1426 }, { 7371 }) -- Boar
mob(1126, "Large Crag Boar", 5, 6, 7, "Dun Morogh", { 1426 }, { 7371 }) -- Boar
mob(1127, "Elder Crag Boar", 5, 7, 8, "Dun Morogh", { 1426 }, { 7371 }) -- Boar
mob(1130, "Bjarn", 4, 12, 12, "Dun Morogh", { 1426 }, { 16828 }) -- Bear
mob(1131, "Winter Wolf", 1, 7, 8, "Dun Morogh", { 1426 }, { 17253 }) -- Wolf
mob(1132, "Timber", 1, 10, 10, "Dun Morogh", { 1426 }, { 17255 }) -- Wolf
mob(1133, "Starving Winter Wolf", 1, 8, 9, "Dun Morogh", { 1426 }, { 17255 }) -- Wolf
mob(1138, "Snow Tracker Wolf", 1, 6, 7, "Dun Morogh", { 1426 }, { 17253 }) -- Wolf
mob(1185, "Wood Lurker", 3, 17, 18, "Loch Modan", { 1432 }, { 17256 }) -- Spider
mob(1189, "Black Bear Patriarch", 4, 16, 17, "Loch Modan", { 1432 }, { 16829 }) -- Bear
mob(1190, "Mountain Boar", 5, 10, 11, "Loch Modan", { 1432 }, { 7371 }) -- Boar
mob(1191, "Mangy Mountain Boar", 5, 14, 15, "Loch Modan", { 1432 }, { 26177 }) -- Boar
mob(1192, "Elder Mountain Boar", 5, 16, 17, "Loch Modan", { 1432 }, { 26177 }) -- Boar
mob(1195, "Forest Lurker", 3, 10, 11, "Loch Modan", { 1432 }, { 17255 }) -- Spider
mob(1196, "Ice Claw Bear", 4, 7, 8, "Dun Morogh", { 1426 }, { 16827 }) -- Bear
mob(1199, "Juvenile Snow Leopard", 2, 5, 6, "Dun Morogh", { 1426 }, { 1742 }) -- Cat
mob(1216, "Shore Crawler", 8, 17, 18, "Westfall", { 1436 }, { 16829 }) -- Crab
mob(1225, "Ol' Sooty", 4, 20, 20, "Loch Modan", { 1432 }, { 16829 }) -- Bear
mob(1258, "Black Ravager Mastiff", 1, 25, 26, "Duskwood", { 1431 }, { 17257, 24605 }) -- Wolf
mob(1505, "Night Web Spider", 3, 3, 4, "Tirisfal Glades", { 1420 }, { 17253 }) -- Spider
mob(1509, "Ragged Scavenger", 1, 2, 3, "Tirisfal Glades", { 1420 }, { 17253 }) -- Wolf
mob(1553, "Greater Duskbat", 24, 6, 7, "Tirisfal Glades", { 1420 }, { 1742 }) -- Bat
mob(1555, "Vicious Night Web Spider", 3, 9, 10, "Tirisfal Glades", { 1420 }, { 17255 }) -- Spider
mob(1557, "Elder Mistvale Gorilla", 9, 40, 41, "Stranglethorn Vale", { 1434 }, { 26187 }) -- Gorilla
mob(1688, "Night Web Matriarch", 3, 5, 5, "Tirisfal Glades", { 1420 }, { 17253 }) -- Spider
mob(1689, "Scarred Crag Boar", 5, 9, 10, "Dun Morogh", { 1426 }, { 7371 }) -- Boar
mob(1693, "Loch Crocolisk", 6, 14, 15, "Loch Modan", { 1432 }, { 17255 }) -- Crocolisk
mob(1713, "Elder Shadowmaw Panther", 2, 42, 43, "Stranglethorn Vale", { 1434 }, { 23109, 24452 }) -- Cat
mob(1765, "Worg", 1, 10, 11, "Silverpine Forest", { 1421 }, { 17255, 24604 }) -- Wolf
mob(1778, "Ferocious Grizzled Bear", 4, 11, 12, "Silverpine Forest", { 1421 }, { 16828 }) -- Bear
mob(1809, "Carrion Vulture", 7, 50, 52, "Western Plaguelands", { 1422 }, { 23148, 24578 }) -- Carrion Bird
mob(1816, "Diseased Grizzly", 4, 55, 56, "Western Plaguelands", { 1422 }, { 3010 }) -- Bear
mob(1817, "Diseased Wolf", 1, 53, 54, "Western Plaguelands", { 1422 }, { 17260 }) -- Wolf
mob(1824, "Plague Lurker", 3, 54, 55, "Western Plaguelands", { 1422 }, { 17260 }) -- Spider
mob(1922, "Gray Forest Wolf", 1, 7, 8, "Elwynn Forest", { 1429 }, { 17253 }) -- Wolf
mob(1923, "Bloodsnout Worg", 1, 16, 17, "Silverpine Forest", { 1421 }, { 17256 }) -- Wolf
mob(1961, "Mangeclaw", 4, 11, 11, "Dun Morogh", { 1426 }, { 16828 }) -- Bear
mob(1984, "Young Thistle Boar", 5, 1, 2, "Teldrassil", { 1438 }, { 7371 }) -- Boar
mob(1985, "Thistle Boar", 5, 2, 3, "Teldrassil", { 1438 }, { 7371 }) -- Boar
mob(1994, "Githyiss the Vile", 3, 5, 5, "Teldrassil", { 1438 }, { 17253 }) -- Spider
mob(1995, "Strigid Owl", 26, 5, 6, "Teldrassil", { 1438 }, { 16827 }) -- Owl
mob(1997, "Strigid Hunter", 26, 8, 9, "Teldrassil", { 1438 }, { 16828 }) -- Owl
mob(1999, "Webwood Venomfang", 3, 7, 8, "Teldrassil", { 1438 }, { 17253 }) -- Spider
mob(2000, "Webwood Silkspinner", 3, 8, 9, "Teldrassil", { 1438 }, { 17255 }) -- Spider
mob(2001, "Giant Webwood Spider", 3, 10, 11, "Teldrassil", { 1438 }, { 17255 }) -- Spider
mob(2042, "Nightsaber", 2, 5, 6, "Teldrassil", { 1438 }, { 1742 }) -- Cat
mob(2070, "Moonstalker Runt", 2, 10, 11, "Darkshore", { 1439 }, { 1742 }) -- Cat
mob(2089, "Giant Wetlands Crocolisk", 6, 25, 26, "Wetlands", { 1437 }, { 17257 }) -- Crocolisk
mob(2163, "Thistle Bear", 4, 11, 12, "Darkshore", { 1439 }, { 16828 }) -- Bear
mob(2232, "Tide Crawler", 8, 12, 14, "Darkshore", { 1439 }, { 16828 }) -- Crab
mob(2237, "Moonstalker Sire", 2, 17, 18, "Darkshore", { 1439 }, { 1753 }) -- Cat
mob(2321, "Foreststrider Fledgling", 12, 11, 13, "Darkshore", { 1439 }, { 1742 }) -- Tallstrider
mob(2323, "Giant Foreststrider", 12, 17, 19, "Darkshore", { 1439 }, { 1753 }) -- Tallstrider
mob(2348, "Elder Moss Creeper", 3, 26, 27, "Hillsbrad Foothills", { 1424 }, { 17257 }) -- Spider
mob(2349, "Giant Moss Creeper", 3, 24, 25, "Hillsbrad Foothills", { 1424 }, { 17257 }) -- Spider
mob(2350, "Forest Moss Creeper", 3, 20, 21, "Hillsbrad Foothills", { 1424 }, { 17256 }) -- Spider
mob(2351, "Gray Bear", 4, 21, 22, "Hillsbrad Foothills", { 1424 }, { 16829 }) -- Bear
mob(2384, "Starving Mountain Lion", 2, 23, 24, "Hillsbrad Foothills", { 1424 }, { 1753 }) -- Cat
mob(2385, "Feral Mountain Lion", 2, 27, 28, "Hillsbrad Foothills", { 1424 }, { 1754 }) -- Cat
mob(2406, "Mountain Lion", 2, 32, 33, "Alterac Mountains", { 1416 }, { 24450 }) -- Cat
mob(2408, "Snapjaw", 21, 30, 31, "Hillsbrad Foothills", { 1424 }, { 17257, 26064 }) -- Turtle
mob(2476, "Large Loch Crocolisk", 6, 22, 22, "Loch Modan", { 1432 }, { 17256 }) -- Crocolisk
mob(2505, "Saltwater Snapjaw", 21, 49, 50, "The Hinterlands", { 1425 }, { 17260 }) -- Turtle
mob(2522, "Jaguero Stalker", 2, 50, 50, "Stranglethorn Vale", { 1434 }, { 1756, 24453 }) -- Cat
mob(2563, "Plains Creeper", 3, 32, 33, "Arathi Highlands", { 1417 }, { 17258 }) -- Spider
mob(2565, "Giant Plains Creeper", 3, 35, 36, "Arathi Highlands", { 1417 }, { 17258 }) -- Spider
mob(2578, "Young Mesa Buzzard", 7, 31, 32, "Arathi Highlands", { 1417 }, { 23145 }) -- Carrion Bird
mob(2579, "Mesa Buzzard", 7, 34, 35, "Arathi Highlands", { 1417 }, { 23145 }) -- Carrion Bird
mob(2681, "Vilebranch Raiding Wolf", 1, 50, 51, "The Hinterlands", { 1425 }, { 17260, 23110 }) -- Wolf
mob(2727, "Crag Coyote", 1, 35, 36, "Badlands", { 1418 }, { 17258, 23099 }) -- Wolf
mob(2728, "Feral Crag Coyote", 1, 37, 38, "Badlands", { 1418 }, { 23099 }) -- Wolf
mob(2729, "Elder Crag Coyote", 1, 39, 40, "Badlands", { 1418 }, { 23099, 24605 }) -- Wolf
mob(2730, "Rabid Crag Coyote", 1, 42, 43, "Badlands", { 1418 }, { 23109 }) -- Wolf
mob(2731, "Ridge Stalker", 2, 36, 37, "Badlands", { 1418 }, { 1755, 24450 }) -- Cat
mob(2732, "Ridge Huntress", 2, 38, 39, "Badlands", { 1418 }, { 1755 }) -- Cat
mob(2734, "Ridge Stalker Patriarch", 2, 40, 41, "Badlands", { 1418 }, { 23109, 24452 }) -- Cat
mob(2753, "Barnabus", 1, 38, 38, "Badlands", { 1418 }, { 17259 }) -- Wolf
mob(2850, "Broken Tooth", 2, 37, 37, "Badlands", { 1418 }, { 23099 }) -- Cat
mob(2924, "Silvermane Wolf", 1, 43, 44, "The Hinterlands", { 1425 }, { 24603 }) -- Wolf
mob(2925, "Silvermane Howler", 1, 45, 46, "The Hinterlands", { 1425 }, { 24605 }) -- Wolf
mob(2926, "Silvermane Stalker", 1, 47, 48, "The Hinterlands", { 1425 }, { 23109 }) -- Wolf
mob(2931, "Zaricotl", 7, 55, 55, "Badlands", { 1418 }, { 23148 }) -- Carrion Bird
mob(2954, "Bristleback Battleboar", 5, 4, 5, "Mulgore", { 1412 }, { 7371 }) -- Boar
mob(2957, "Elder Plainstrider", 12, 8, 9, "Mulgore", { 1412 }, { 1742 }) -- Tallstrider
mob(2958, "Prairie Wolf", 1, 5, 6, "Mulgore", { 1412 }, { 17253 }) -- Wolf
mob(2959, "Prairie Stalker", 1, 7, 8, "Mulgore", { 1412 }, { 17253 }) -- Wolf
mob(2960, "Prairie Wolf Alpha", 1, 9, 10, "Mulgore", { 1412 }, { 17255, 24604 }) -- Wolf
mob(2966, "Battleboar", 5, 3, 4, "Mulgore", { 1412 }, { 7371 }) -- Boar
mob(3035, "Flatland Cougar", 2, 7, 8, "Mulgore", { 1412 }, { 1742 }) -- Cat
mob(3068, "Mazzranache", 12, 9, 9, "Mulgore", { 1412 }, { 1742 }) -- Tallstrider
mob(3098, "Mottled Boar", 5, 1, 2, "Durotar", { 1411 }, { 7371 }) -- Boar
mob(3099, "Dire Mottled Boar", 5, 6, 7, "Durotar", { 1411 }, { 7371 }) -- Boar
mob(3100, "Elder Mottled Boar", 5, 8, 9, "Durotar", { 1411 }, { 7371 }) -- Boar
mob(3106, "Pygmy Surf Crawler", 8, 5, 6, "Durotar", { 1411 }, { 16827 }) -- Crab
mob(3108, "Encrusted Surf Crawler", 8, 9, 10, "Durotar", { 1411 }, { 16828 }) -- Crab
mob(3110, "Dreadmaw Crocolisk", 6, 9, 11, "Durotar", { 1411 }, { 17253 }) -- Crocolisk
mob(3121, "Durotar Tiger", 2, 7, 8, "Durotar", { 1411 }, { 1742 }) -- Cat
mob(3124, "Scorpid Worker", 20, 3, 3, "Durotar", { 1411 }, { 16827 }) -- Scorpid
mob(3127, "Venomtail Scorpid", 20, 9, 10, "Durotar", { 1411 }, { 16828, 24640 }) -- Scorpid
mob(3225, "Corrupted Mottled Boar", 5, 10, 11, "Durotar", { 1411 }, { 7371 }) -- Boar
mob(3226, "Corrupted Scorpid", 20, 10, 11, "Durotar", { 1411 }, { 24640 }) -- Scorpid
mob(3241, "Savannah Patriarch", 2, 15, 16, "The Barrens", { 1413 }, { 1753 }) -- Cat
mob(3245, "Ornery Plainstrider", 12, 16, 17, "The Barrens", { 1413 }, { 1753 }) -- Tallstrider
mob(3246, "Fleeting Plainstrider", 12, 12, 13, "The Barrens", { 1413 }, { 1742 }) -- Tallstrider
mob(3247, "Thunderhawk Hatchling", 27, 18, 20, "The Barrens", { 1413 }, { 25008 }) -- Wind Serpent
mob(3249, "Greater Thunderhawk", 27, 23, 24, "The Barrens", { 1413 }, { 25008 }) -- Wind Serpent
mob(3250, "Silithid Creeper", 20, 20, 21, "The Barrens", { 1413 }, { 24640 }) -- Scorpid
mob(3252, "Silithid Swarmer", 20, 21, 22, "The Barrens", { 1413 }, { 24640 }) -- Scorpid
mob(3281, "Sarkoth", 20, 4, 4, "Durotar", { 1411 }, { 16827 }) -- Scorpid
mob(3424, "Thunderhawk Cloudscraper", 27, 20, 22, "The Barrens", { 1413 }, { 25008 }) -- Wind Serpent
mob(3461, "Oasis Snapjaw", 21, 15, 16, "The Barrens", { 1413 }, { 17255 }) -- Turtle
mob(3472, "Washte Pawne", 27, 25, 25, "The Barrens", { 1413 }, { 25009 }) -- Wind Serpent
mob(3581, "Sewer Beast", 6, 50, 50, "Stormwind City", { 1453 }, { 17260 }) -- Crocolisk
mob(3619, "Ghost Saber", 2, 19, 20, "Darkshore", { 1439 }, { 16829 }) -- Cat
mob(3630, "Deviate Coiler", 27, 15, 16, "Wailing Caverns (Dungeon)", { -43 }, { 25008 }) -- Wind Serpent
mob(3631, "Deviate Stinglash", 27, 16, 17, "Wailing Caverns (Dungeon)", { -43 }, { 25008 }) -- Wind Serpent
mob(3653, "Kresh", 21, 20, 20, "Wailing Caverns (Dungeon)", { -43 }, { 17256, 26064 }) -- Turtle
mob(3809, "Ashenvale Bear", 4, 21, 22, "Ashenvale", { 1440 }, { 16829 }) -- Bear
mob(3810, "Elder Ashenvale Bear", 4, 25, 26, "Ashenvale", { 1440 }, { 16830 }) -- Bear
mob(3812, "Clattering Crawler", 8, 19, 20, "Ashenvale", { 1440 }, { 16829 }) -- Crab
mob(3821, "Wildthorn Lurker", 3, 28, 29, "Ashenvale", { 1440 }, { 17257 }) -- Spider
mob(3823, "Ghostpaw Runner", 1, 19, 20, "Ashenvale", { 1440 }, { 17256 }) -- Wolf
mob(3825, "Ghostpaw Alpha", 1, 27, 28, "Ashenvale", { 1440 }, { 17257, 24605 }) -- Wolf
mob(4005, "Deepmoss Creeper", 3, 16, 17, "Stonetalon Mountains", { 1442 }, { 17256 }) -- Spider
mob(4006, "Deepmoss Webspinner", 3, 19, 20, "Stonetalon Mountains", { 1442 }, { 17256 }) -- Spider
mob(4067, "Twilight Runner", 2, 23, 24, "Stonetalon Mountains", { 1442 }, { 1753 }) -- Cat
mob(4117, "Cloud Serpent", 27, 25, 26, "Thousand Needles", { 1441 }, { 25009 }) -- Wind Serpent
mob(4118, "Venomous Cloud Serpent", 27, 26, 28, "Thousand Needles", { 1441 }, { 25009 }) -- Wind Serpent
mob(4119, "Elder Cloud Serpent", 27, 27, 29, "Thousand Needles", { 1441 }, { 25009 }) -- Wind Serpent
mob(4126, "Crag Stalker", 2, 25, 26, "Thousand Needles", { 1441 }, { 1754 }) -- Cat
mob(4139, "Scorpid Terror", 20, 33, 34, "Thousand Needles", { 1441 }, { 24583 }) -- Scorpid
mob(4140, "Scorpid Reaver", 20, 31, 32, "Thousand Needles", { 1441 }, { 16830, 24583 }) -- Scorpid
mob(4143, "Sparkleshell Snapper", 21, 34, 35, "Thousand Needles", { 1441 }, { 17258 }) -- Turtle
mob(4158, "Salt Flats Vulture", 7, 32, 34, "Thousand Needles", { 1441 }, { 24577 }) -- Carrion Bird
mob(4304, "Scarlet Tracking Hound", 25, 33, 34, "Scarlet Monastery (Dungeon)", { -189 }, { 23099 }) -- Hyena
mob(4341, "Drywallow Crocolisk", 6, 35, 36, "Dustwallow Marsh", { 1445 }, { 17258 }) -- Crocolisk
mob(4343, "Drywallow Snapper", 6, 37, 38, "Dustwallow Marsh", { 1445 }, { 16831 }) -- Crocolisk
mob(4344, "Mottled Drywallow Crocolisk", 6, 38, 39, "Dustwallow Marsh", { 1445 }, { 17258 }) -- Crocolisk
mob(4345, "Drywallow Daggermaw", 6, 40, 41, "Dustwallow Marsh", { 1445 }, { 17259 }) -- Crocolisk
mob(4396, "Mudrock Tortoise", 21, 36, 37, "Dustwallow Marsh", { 1445 }, { 17258 }) -- Turtle
mob(4400, "Mudrock Snapjaw", 21, 41, 42, "Dustwallow Marsh", { 1445 }, { 17259 }) -- Turtle
mob(4411, "Darkfang Lurker", 3, 36, 37, "Dustwallow Marsh", { 1445 }, { 17258 }) -- Spider
mob(4412, "Darkfang Creeper", 3, 38, 39, "Dustwallow Marsh", { 1445 }, { 17258 }) -- Spider
mob(4413, "Darkfang Spider", 3, 35, 36, "Dustwallow Marsh", { 1445 }, { 17258 }) -- Spider
mob(4511, "Agam'ar", 5, 24, 25, "Razorfen Kraul (Dungeon)", { -47 }, { 26178 }) -- Boar
mob(4512, "Rotting Agam'ar", 5, 28, 28, "Razorfen Kraul (Dungeon)", { -47 }, { 26178 }) -- Boar
mob(4514, "Raging Agam'ar", 5, 25, 26, "Razorfen Kraul (Dungeon)", { -47 }, { 26178 }) -- Boar
mob(4538, "Kraul Bat", 24, 30, 31, "Razorfen Kraul (Dungeon)", { -47 }, { 1754, 23145 }) -- Bat
mob(4539, "Greater Kraul Bat", 24, 32, 32, "Razorfen Kraul (Dungeon)", { -47 }, { 1754, 23145 }) -- Bat
mob(4662, "Magram Bonepaw", 25, 37, 38, "Desolace", { 1443 }, { 23099 }) -- Hyena
mob(4688, "Bonepaw Hyena", 25, 33, 35, "Desolace", { 1443 }, { 23099 }) -- Hyena
mob(4693, "Dread Flyer", 7, 36, 37, "Desolace", { 1443 }, { 23145 }) -- Carrion Bird
mob(4694, "Dread Ripper", 7, 39, 40, "Desolace", { 1443 }, { 24577 }) -- Carrion Bird
mob(4696, "Scorpashi Snapper", 20, 30, 31, "Desolace", { 1443 }, { 16830, 24583 }) -- Scorpid
mob(4697, "Scorpashi Lasher", 20, 34, 35, "Desolace", { 1443 }, { 16831 }) -- Scorpid
mob(4699, "Scorpashi Venomlash", 20, 38, 39, "Desolace", { 1443 }, { 24583 }) -- Scorpid
mob(4821, "Skittering Crustacean", 8, 22, 23, "Blackfathom Deeps (Dungeon)", { -48 }, { 16829 }) -- Crab
mob(4822, "Snapping Crustacean", 8, 23, 24, "Blackfathom Deeps (Dungeon)", { -48 }, { 16829 }) -- Crab
mob(4823, "Barbed Crustacean", 8, 25, 26, "Blackfathom Deeps (Dungeon)", { -48 }, { 16830 }) -- Crab
mob(4824, "Aku'mai Fisher", 21, 23, 24, "Blackfathom Deeps (Dungeon)", { -48 }, { 17256, 26064 }) -- Turtle
mob(4825, "Aku'mai Snapjaw", 21, 26, 27, "Blackfathom Deeps (Dungeon)", { -48 }, { 17257, 26064 }) -- Turtle
mob(4841, "Deadmire", 6, 45, 45, "Dustwallow Marsh", { 1445 }, { 17259 }) -- Crocolisk
mob(4861, "Shrike Bat", 24, 38, 39, "Uldaman (Dungeon)", { -70 }, { 1755, 23145, 24577 }) -- Bat
mob(4887, "Ghamoo-ra", 21, 25, 25, "Blackfathom Deeps (Dungeon)", { -48 }, { 17257, 26064 }) -- Turtle
mob(4950, "Spot", 1, 35, 35, "Dustwallow Marsh", { 1445 }, { 23099 }) -- Wolf
mob(5053, "Deviate Crocolisk", 6, 18, 19, "Wailing Caverns (Dungeon)", { -43 }, { 17256 }) -- Crocolisk
mob(5056, "Deviate Dreadfang", 27, 20, 21, "Wailing Caverns (Dungeon)", { -43 }, { 25008 }) -- Wind Serpent
mob(5262, "Groddoc Thunderer", 9, 49, 50, "Feralas", { 1444 }, { 26187 }) -- Gorilla
mob(5268, "Ironfur Bear", 4, 41, 42, "Feralas", { 1444 }, { 16832 }) -- Bear
mob(5274, "Ironfur Patriarch", 4, 48, 49, "Feralas", { 1444 }, { 3010 }) -- Bear
mob(5286, "Longtooth Runner", 1, 40, 41, "Feralas", { 1444 }, { 17259, 23109, 24603 }) -- Wolf
mob(5287, "Longtooth Howler", 1, 43, 44, "Feralas", { 1444 }, { 24605 }) -- Wolf
mob(5291, "Hakkari Frostwing", 27, 49, 50, "The Temple of Atal'Hakkar (Dungeon)", { -109 }, { 25011 }) -- Wind Serpent
mob(5307, "Vale Screecher", 27, 41, 43, "Feralas", { 1444 }, { 23147, 25010 }) -- Wind Serpent
mob(5308, "Rogue Vale Screecher", 27, 44, 46, "Feralas", { 1444 }, { 23147, 25010 }) -- Wind Serpent
mob(5349, "Arash-ethis", 27, 49, 49, "Feralas", { 1444 }, { 23147, 25011 }) -- Wind Serpent
mob(5352, "Old Grizzlegut", 4, 43, 43, "Feralas", { 1444 }, { 16832 }) -- Bear
mob(5356, "Snarler", 1, 42, 42, "Feralas", { 1444 }, { 17259, 24603 }) -- Wolf
mob(5422, "Scorpid Hunter", 20, 40, 41, "Tanaris", { 1446 }, { 16832, 24586 }) -- Scorpid
mob(5423, "Scorpid Tail Lasher", 20, 43, 44, "Tanaris", { 1446 }, { 24586 }) -- Scorpid
mob(5424, "Scorpid Dunestalker", 20, 46, 47, "Tanaris", { 1446 }, { 24586 }) -- Scorpid
mob(5425, "Starving Blisterpaw", 25, 41, 42, "Tanaris", { 1446 }, { 23109 }) -- Hyena
mob(5426, "Blisterpaw Hyena", 25, 44, 45, "Tanaris", { 1446 }, { 23109 }) -- Hyena
mob(5427, "Rabid Blisterpaw", 25, 47, 48, "Tanaris", { 1446 }, { 23109 }) -- Hyena
mob(5428, "Roc", 7, 42, 43, "Tanaris", { 1446 }, { 23147 }) -- Carrion Bird
mob(5429, "Fire Roc", 7, 43, 45, "Tanaris", { 1446 }, { 23147 }) -- Carrion Bird
mob(5430, "Searing Roc", 7, 47, 49, "Tanaris", { 1446 }, { 23147 }) -- Carrion Bird
mob(5708, "Spawn of Hakkar", 27, 51, 51, "The Temple of Atal'Hakkar (Dungeon)", { -109 }, { 23148, 25011 }) -- Wind Serpent
mob(5756, "Deviate Venomwing", 27, 20, 21, "Wailing Caverns (Dungeon)", { -43 }, { 25008 }) -- Wind Serpent
mob(5823, "Death Flayer", 20, 11, 11, "Durotar", { 1411 }, { 16828, 24640 }) -- Scorpid
mob(5937, "Vile Sting", 20, 35, 35, "Thousand Needles", { 1441 }, { 16831, 24583 }) -- Scorpid
mob(5988, "Scorpok Stinger", 20, 50, 51, "Blasted Lands", { 1419 }, { 24586 }) -- Scorpid
mob(5992, "Ashmane Boar", 5, 48, 49, "Blasted Lands", { 1419 }, { 26201 }) -- Boar
mob(6013, "Wayward Buzzard", 7, 35, 37, "Badlands", { 1418 }, { 23145 }) -- Carrion Bird
mob(6516, "Un'Goro Thunderer", 9, 52, 53, "Un'Goro Crater", { 1449 }, { 26188 }) -- Gorilla
mob(6585, "Uhk'loc", 9, 52, 52, "Un'Goro Crater", { 1449 }, { 17260 }) -- Gorilla
mob(6788, "Den Mother", 4, 18, 19, "Darkshore", { 1439 }, { 16829 }) -- Bear
mob(7022, "Venomlash Scorpid", 20, 39, 40, "Uldaman (Dungeon)", { -70 }, { 16831 }) -- Scorpid
mob(7055, "Blackrock Worg", 1, 54, 55, "Burning Steppes", { 1428 }, { 23110 }) -- Wolf
mob(7078, "Cleft Scorpid", 20, 35, 36, "Uldaman (Dungeon)", { -70 }, { 24583 }) -- Scorpid
mob(7097, "Ironbeak Owl", 26, 48, 49, "Felwood", { 1448 }, { 23147, 24578 }) -- Owl
mob(7098, "Ironbeak Screecher", 26, 52, 53, "Felwood", { 1448 }, { 23148 }) -- Owl
mob(7099, "Ironbeak Hunter", 26, 50, 51, "Felwood", { 1448 }, { 3010, 23148 }) -- Owl
mob(7319, "Lady Sathrah", 3, 12, 12, "Teldrassil", { 1438 }, { 17255 }) -- Spider
mob(7405, "Deadly Cleft Scorpid", 20, 42, 43, "Uldaman (Dungeon)", { -70 }, { 24586 }) -- Scorpid
mob(7430, "Frostsaber Cub", 2, 55, 56, "Winterspring", { 1452 }, { 16697 }) -- Cat
mob(7432, "Frostsaber Stalker", 2, 59, 60, "Winterspring", { 1452 }, { 23110, 24453 }) -- Cat
mob(7433, "Frostsaber Huntress", 2, 58, 59, "Winterspring", { 1452 }, { 23110 }) -- Cat
mob(7444, "Shardtooth Bear", 4, 53, 54, "Winterspring", { 1452 }, { 3010 }) -- Bear
mob(7445, "Elder Shardtooth", 4, 57, 58, "Winterspring", { 1452 }, { 3009 }) -- Bear
mob(7455, "Winterspring Owl", 26, 54, 56, "Winterspring", { 1452 }, { 3010, 23148 }) -- Owl
mob(7456, "Winterspring Screecher", 26, 57, 59, "Winterspring", { 1452 }, { 3009, 23148, 24579 }) -- Owl
mob(7803, "Scorpid Duneburrower", 20, 46, 47, "Tanaris", { 1446 }, { 24586 }) -- Scorpid
mob(8207, "Greater Firebird", 7, 46, 46, "Tanaris", { 1446 }, { 23147 }) -- Carrion Bird
mob(8208, "Murderous Blisterpaw", 25, 43, 43, "Tanaris", { 1446 }, { 23109 }) -- Hyena
mob(8211, "Old Cliff Jumper", 1, 42, 42, "The Hinterlands", { 1425 }, { 17259, 23109 }) -- Wolf
mob(8213, "Ironback", 21, 51, 51, "The Hinterlands", { 1425 }, { 17260 }) -- Turtle
mob(8277, "Rekk'tilac", 3, 48, 48, "Searing Gorge", { 1427 }, { 17260 }) -- Spider
mob(8299, "Spiteflayer", 7, 52, 52, "Blasted Lands", { 1419 }, { 23148 }) -- Carrion Bird
mob(8300, "Ravage", 25, 51, 51, "Blasted Lands", { 1419 }, { 23110 }) -- Hyena
mob(8301, "Clack the Reaver", 20, 53, 53, "Blasted Lands", { 1419 }, { 3010 }) -- Scorpid
mob(8303, "Grunter", 5, 50, 50, "Blasted Lands", { 1419 }, { 23110, 26201 }) -- Boar
mob(8336, "Hakkari Sapper", 27, 49, 50, "The Temple of Atal'Hakkar (Dungeon)", { -109 }, { 25011 }) -- Wind Serpent
mob(8600, "Plaguebat", 24, 53, 55, "Eastern Plaguelands", { 1423 }, { 1756, 23148 }) -- Bat
mob(8601, "Noxious Plaguebat", 24, 54, 56, "Eastern Plaguelands", { 1423 }, { 1756 }) -- Bat
mob(8602, "Monstrous Plaguebat", 24, 56, 58, "Eastern Plaguelands", { 1423 }, { 16697, 24579 }) -- Bat
mob(8762, "Timberweb Recluse", 3, 47, 48, "Azshara", { 1447 }, { 17259 }) -- Spider
mob(8926, "Deep Stinger", 20, 50, 52, "Blackrock Depths (Dungeon)", { -230 }, { 24586 }) -- Scorpid
mob(8927, "Dark Screecher", 24, 50, 52, "Blackrock Depths (Dungeon)", { -230 }, { 23148, 24578 }) -- Bat
mob(8933, "Cave Creeper", 3, 50, 52, "Blackrock Depths (Dungeon)", { -230 }, { 17260 }) -- Spider
mob(8958, "Angerclaw Mauler", 4, 49, 50, "Felwood", { 1448 }, { 3010 }) -- Bear
mob(8959, "Felpaw Wolf", 1, 47, 48, "Felwood", { 1448 }, { 17259, 24603 }) -- Wolf
mob(8961, "Felpaw Ravager", 1, 51, 52, "Felwood", { 1448 }, { 17260 }) -- Wolf
mob(9416, "Scarshield Worg", 1, 53, 54, "Blackrock Spire (Dungeon)", { -229 }, { 23110 }) -- Wolf
mob(9622, "U'cha", 9, 55, 55, "Un'Goro Crater", { 1449 }, { 26188 }) -- Gorilla
mob(9691, "Venomtip Scorpid", 20, 52, 53, "Burning Steppes", { 1428 }, { 24586 }) -- Scorpid
mob(9695, "Deathlash Scorpid", 20, 54, 55, "Burning Steppes", { 1428 }, { 3010, 24586 }) -- Scorpid
mob(9696, "Bloodaxe Worg", 1, 56, 57, "Blackrock Spire (Dungeon)", { -229 }, { 17261, 23110, 24597 }) -- Wolf
mob(9698, "Firetail Scorpid", 20, 56, 57, "Burning Steppes", { 1428 }, { 24587 }) -- Scorpid
mob(10200, "Rak'Shiri", 2, 57, 57, "Winterspring", { 1452 }, { 23110 }) -- Cat
mob(10644, "Mist Howler", 1, 22, 22, "Ashenvale", { 1440 }, { 24604 }) -- Wolf
mob(11357, "Son of Hakkar", 27, 60, 60, "Zul'Gurub (Raid)", { -309 }, { 25012 }) -- Wind Serpent
mob(11365, "Zulian Panther", 2, 60, 60, "Zul'Gurub (Raid)", { -309 }, { 23110 }) -- Cat
mob(11735, "Stonelash Scorpid", 20, 54, 55, "Silithus", { 1451 }, { 24586 }) -- Scorpid
mob(11736, "Stonelash Pincer", 20, 56, 57, "Silithus", { 1451 }, { 24587 }) -- Scorpid
mob(11737, "Stonelash Flayer", 20, 58, 59, "Silithus", { 1451 }, { 24587 }) -- Scorpid
mob(11921, "Besseleth", 3, 21, 21, "Stonetalon Mountains", { 1442 }, { 17256 }) -- Spider
mob(14223, "Cranky Benj", 21, 32, 32, "Alterac Mountains", { 1416 }, { 17257, 26064 }) -- Turtle
mob(14233, "Ripscale", 6, 39, 39, "Dustwallow Marsh", { 1445 }, { 17259 }) -- Crocolisk
mob(14266, "Shanda the Spinner", 3, 19, 19, "Loch Modan", { 1432 }, { 17256 }) -- Spider
mob(14279, "Creepthess", 3, 24, 24, "Hillsbrad Foothills", { 1424 }, { 17256 }) -- Spider
mob(14339, "Death Howl", 1, 49, 49, "Felwood", { 1448 }, { 17259, 24603 }) -- Wolf
mob(14343, "Olm the Wise", 26, 52, 52, "Felwood", { 1448 }, { 3010, 23148 }) -- Owl
mob(14344, "Mongress", 4, 50, 50, "Felwood", { 1448 }, { 3010 }) -- Bear
mob(14476, "Krellack", 20, 56, 56, "Silithus", { 1451 }, { 24587 }) -- Scorpid
mob(16117, "Plagued Swine", 5, 60, 60, "Eastern Plaguelands", { 1423 }, { 27685 }) -- Boar
-- DATA_END
