local ADDON_NAME, ns = ...

-- Warlock demon abilities for TBC Classic: every rank a demon can learn.
-- Demons train differently from hunter pets: each trainable rank is a
-- GRIMOIRE item sold by Demon Trainer vendors (money cost, required
-- warlock level); rank 1 of a demon's core attack comes with the demon.
-- No training points, no taming. Spell IDs / rank order from the 2.5
-- client DB (SkillLineAbility), costs/levels from the grimoire items
-- (ItemSparse joined via ItemEffect -> SpellEffect LEARN_SPELL).
-- Generated by Generate-WarlockPetData.ps1 - do not hand-edit.
--
-- ability(key, familyId): CreatureFamily ID of the one demon that uses it.
-- rank(spellId, rank, warlockLevel, source, moneyCost, grimoireItemId):
-- source "g" = grimoire (demon trainer vendor), "a" = automatic.

ns.DEMON_FAMILIES = {
    [15] = "Felhunter",
    [16] = "Voidwalker",
    [17] = "Succubus",
    [23] = "Imp",
    [29] = "Felguard",
}

-- Localized UnitCreatureFamily("pet") -> family ID, every client locale.
-- The Incubus (Era's alternate Succubus appearance) aliases to Succubus.
ns.DEMON_FAMILY_BY_NAME = {
    ["Felhunter"] = 15,
    ["Teufelsjäger"] = 15,
    ["Chasseur corrompu"] = 15,
    ["Manáfago"] = 15,
    ["Caçador Vil"] = 15,
    ["Охотник Скверны"] = 15,
    ["지옥사냥개"] = 15,
    ["地狱猎犬"] = 15,
    ["惡魔獵犬"] = 15,
    ["Voidwalker"] = 16,
    ["Leerwandler"] = 16,
    ["Marcheur du Vide"] = 16,
    ["Abisario"] = 16,
    ["Emissário do Caos"] = 16,
    ["Демон Бездны"] = 16,
    ["보이드워커"] = 16,
    ["虚空行者"] = 16,
    ["虛無行者"] = 16,
    ["Succubus"] = 17,
    ["Incubus"] = 17,
    ["Sukkubus"] = 17,
    ["Inkubus"] = 17,
    ["Succube"] = 17,
    ["Incube"] = 17,
    ["Súcubo"] = 17,
    ["Íncubos"] = 17,
    ["Íncubo"] = 17,
    ["Суккуб"] = 17,
    ["Инкуб"] = 17,
    ["서큐버스"] = 17,
    ["인큐버스"] = 17,
    ["魅魔"] = 17,
    ["夜魔"] = 17,
    ["夢魔"] = 17,
    ["Imp"] = 23,
    ["Wichtel"] = 23,
    ["Diablotin"] = 23,
    ["Diablillo"] = 23,
    ["Diabrete"] = 23,
    ["Бес"] = 23,
    ["임프"] = 23,
    ["小鬼"] = 23,
    ["Felguard"] = 29,
    ["Teufelswache"] = 29,
    ["Gangregarde"] = 29,
    ["Guardia vil"] = 29,
    ["Guarda Vil"] = 29,
    ["Страж Скверны"] = 29,
    ["지옥수호병"] = 29,
    ["恶魔卫士"] = 29,
    ["惡魔守衛"] = 29,
}

local ability, rank = ns.NewDemonAbilityDB()

-- DATA_START (generated by Generate-WarlockPetData.ps1; do not hand-edit)
ability("bloodpact", 23) -- Blood Pact: Imp
rank(6307, 1, 4, "g", 100, 16321) -- Grimoire of Blood Pact (Rank 1)
rank(7804, 2, 14, "g", 900, 16322) -- Grimoire of Blood Pact (Rank 2)
rank(7805, 3, 26, "g", 4000, 16323) -- Grimoire of Blood Pact (Rank 3)
rank(11766, 4, 38, "g", 10000, 16324) -- Grimoire of Blood Pact (Rank 4)
rank(11767, 5, 50, "g", 15000, 16325) -- Grimoire of Blood Pact (Rank 5)
rank(27268, 6, 62, "g", 26000, 22180) -- Grimoire of Blood Pact (Rank 6)
ability("fireshield", 23) -- Fire Shield: Imp
rank(2947, 1, 14, "g", 900, 16326) -- Grimoire of Fire Shield (Rank 1)
rank(8316, 2, 24, "g", 3000, 16327) -- Grimoire of Fire Shield (Rank 2)
rank(8317, 3, 34, "g", 8000, 16328) -- Grimoire of Fire Shield (Rank 3)
rank(11770, 4, 44, "g", 12000, 16329) -- Grimoire of Fire Shield (Rank 4)
rank(11771, 5, 54, "g", 20000, 16330) -- Grimoire of Fire Shield (Rank 5)
rank(27269, 6, 64, "g", 36000, 22181) -- Grimoire of Fire Shield (Rank 6)
ability("firebolt", 23) -- Firebolt: Imp
rank(3110, 1, 1, "a", 0, nil) -- Firebolt 1 (comes with the demon)
rank(7799, 2, 8, "g", 100, 16302) -- Grimoire of Firebolt (Rank 2)
rank(7800, 3, 18, "g", 1500, 16316) -- Grimoire of Firebolt (Rank 3)
rank(7801, 4, 28, "g", 5000, 16317) -- Grimoire of Firebolt (Rank 4)
rank(7802, 5, 38, "g", 10000, 16318) -- Grimoire of Firebolt (Rank 5)
rank(11762, 6, 48, "g", 14000, 16319) -- Grimoire of Firebolt (Rank 6)
rank(11763, 7, 58, "g", 24000, 16320) -- Grimoire of Firebolt (Rank 7)
rank(27267, 8, 68, "g", 54000, 22179) -- Grimoire of Firebolt (Rank 8)
ability("phaseshift", 23) -- Phase Shift: Imp
rank(4511, 1, 12, "g", 600, 16331) -- Grimoire of Phase Shift
ability("consumeshadows", 16) -- Consume Shadows: Voidwalker
rank(17767, 1, 18, "g", 1500, 16357) -- Grimoire of Consume Shadows (Rank 1)
rank(17850, 2, 26, "g", 4000, 16358) -- Grimoire of Consume Shadows (Rank 2)
rank(17851, 3, 34, "g", 8000, 16359) -- Grimoire of Consume Shadows (Rank 3)
rank(17852, 4, 42, "g", 11000, 16360) -- Grimoire of Consume Shadows (Rank 4)
rank(17853, 5, 50, "g", 15000, 16361) -- Grimoire of Consume Shadows (Rank 5)
rank(17854, 6, 58, "g", 24000, 16362) -- Grimoire of Consume Shadows (Rank 6)
rank(27272, 7, 66, "g", 44000, 22184) -- Grimoire of Consume Shadows (Rank 7)
ability("sacrifice", 16) -- Sacrifice: Voidwalker
rank(7812, 1, 16, "g", 1200, 16351) -- Grimoire of Sacrifice (Rank 1)
rank(19438, 2, 24, "g", 3000, 16352) -- Grimoire of Sacrifice (Rank 2)
rank(19440, 3, 32, "g", 7000, 16353) -- Grimoire of Sacrifice (Rank 3)
rank(19441, 4, 40, "g", 11000, 16354) -- Grimoire of Sacrifice (Rank 4)
rank(19442, 5, 48, "g", 14000, 16355) -- Grimoire of Sacrifice (Rank 5)
rank(19443, 6, 56, "g", 22000, 16356) -- Grimoire of Sacrifice (Rank 6)
rank(27273, 7, 64, "g", 36000, 22185) -- Grimoire of Sacrifice (Rank 7)
ability("suffering", 16) -- Suffering: Voidwalker
rank(17735, 1, 24, "g", 3000, 16363) -- Grimoire of Suffering (Rank 1)
rank(17750, 2, 36, "g", 9000, 16364) -- Grimoire of Suffering (Rank 2)
rank(17751, 3, 48, "g", 14000, 16365) -- Grimoire of Suffering (Rank 3)
rank(17752, 4, 60, "g", 26000, 16366) -- Grimoire of Suffering (Rank 4)
rank(27271, 5, 63, "g", 32000, 22183) -- Grimoire of Suffering (Rank 5)
rank(33701, 6, 69, "g", 60000, 28068) -- Grimoire of Suffering (Rank 6)
ability("torment", 16) -- Torment: Voidwalker
rank(3716, 1, 10, "a", 0, nil) -- Torment 1 (comes with the demon)
rank(7809, 2, 20, "g", 2000, 16346) -- Grimoire of Torment (Rank 2)
rank(7810, 3, 30, "g", 6000, 16347) -- Grimoire of Torment (Rank 3)
rank(7811, 4, 40, "g", 11000, 16348) -- Grimoire of Torment (Rank 4)
rank(11774, 5, 50, "g", 15000, 16349) -- Grimoire of Torment (Rank 5)
rank(11775, 6, 60, "g", 26000, 16350) -- Grimoire of Torment (Rank 6)
rank(27270, 7, 70, "g", 67000, 22182) -- Grimoire of Torment (Rank 7)
ability("lashofpain", 17) -- Lash of Pain: Succubus
rank(7814, 1, 20, "a", 0, nil) -- Lash of Pain 1 (comes with the demon)
rank(7815, 2, 28, "g", 5000, 16368) -- Grimoire of Lash of Pain (Rank 2)
rank(7816, 3, 36, "g", 9000, 16371) -- Grimoire of Lash of Pain (Rank 3)
rank(11778, 4, 44, "g", 12000, 16372) -- Grimoire of Lash of Pain (Rank 4)
rank(11779, 5, 52, "g", 18000, 16373) -- Grimoire of Lash of Pain (Rank 5)
rank(11780, 6, 60, "g", 26000, 16374) -- Grimoire of Lash of Pain (Rank 6)
rank(27274, 7, 68, "g", 54000, 22186) -- Grimoire of Lash of Pain (Rank 7)
ability("lesserinvisibility", 17) -- Lesser Invisibility: Succubus
rank(7870, 1, 32, "g", 7000, 16380) -- Grimoire of Lesser Invisibility
ability("seduction", 17) -- Seduction: Succubus
rank(6358, 1, 26, "g", 4000, 16379) -- Grimoire of Seduction
ability("soothingkiss", 17) -- Soothing Kiss: Succubus
rank(6360, 1, 22, "g", 2500, 16375) -- Grimoire of Soothing Kiss (Rank 1)
rank(7813, 2, 34, "g", 8000, 16376) -- Grimoire of Soothing Kiss (Rank 2)
rank(11784, 3, 46, "g", 13000, 16377) -- Grimoire of Soothing Kiss (Rank 3)
rank(11785, 4, 58, "g", 24000, 16378) -- Grimoire of Soothing Kiss (Rank 4)
rank(27275, 5, 70, "g", 67000, 22187) -- Grimoire of Soothing Kiss (Rank 5)
ability("devourmagic", 15) -- Devour Magic: Felhunter
rank(19505, 1, 30, "a", 0, nil) -- Devour Magic 1 (comes with the demon)
rank(19731, 2, 38, "g", 10000, 16381) -- Grimoire of Devour Magic (Rank 2)
rank(19734, 3, 46, "g", 13000, 16382) -- Grimoire of Devour Magic (Rank 3)
rank(19736, 4, 54, "g", 20000, 16383) -- Grimoire of Devour Magic (Rank 4)
rank(27276, 5, 62, "g", 29000, 22188) -- Grimoire of Devour Magic (Rank 5)
rank(27277, 6, 70, "g", 67000, 22189) -- Grimoire of Devour Magic (Rank 6)
ability("paranoia", 15) -- Paranoia: Felhunter
rank(19480, 1, 42, "g", 11000, 16390) -- Grimoire of Paranoia
ability("spelllock", 15) -- Spell Lock: Felhunter
rank(19244, 1, 36, "g", 9000, 16388) -- Grimoire of Spell Lock (Rank 1)
rank(19647, 2, 52, "g", 18000, 16389) -- Grimoire of Spell Lock (Rank 2)
ability("taintedblood", 15) -- Tainted Blood: Felhunter
rank(19478, 1, 32, "g", 7000, 16384) -- Grimoire of Tainted Blood (Rank 1)
rank(19655, 2, 40, "g", 11000, 16385) -- Grimoire of Tainted Blood (Rank 2)
rank(19656, 3, 48, "g", 14000, 16386) -- Grimoire of Tainted Blood (Rank 3)
rank(19660, 4, 56, "g", 22000, 16387) -- Grimoire of Tainted Blood (Rank 4)
rank(27280, 5, 64, "g", 36000, 22190) -- Grimoire of Tainted Blood (Rank 5)
ability("anguish", 29) -- Anguish: Felguard
rank(33698, 1, 50, "g", 15000, 28071) -- Grimoire of Anguish (Rank 1)
rank(33699, 2, 60, "g", 26000, 28072) -- Grimoire of Anguish (Rank 2)
rank(33700, 3, 70, "g", 67000, 28073) -- Grimoire of Anguish (Rank 3)
ability("avoidance", 29) -- Avoidance: Felguard
rank(32233, 1, 60, "g", 26000, 25469) -- Grimoire of Avoidance
ability("cleave", 29) -- Cleave: Felguard
rank(30213, 1, 50, "g", 15000, 23734) -- Grimoire of Cleave (Rank 1)
rank(30219, 2, 60, "g", 15000, 23745) -- Grimoire of Cleave (Rank 2)
rank(30223, 3, 68, "g", 60000, 23755) -- Grimoire of Cleave (Rank 3)
ability("demonicfrenzy", 29) -- Demonic Frenzy: Felguard
rank(32850, 1, 56, "g", 22000, 25900) -- Grimoire of Demonic Frenzy
ability("intercept", 29) -- Intercept: Felguard
rank(30151, 1, 52, "g", 18000, 23711) -- Grimoire of Intercept (Rank 1)
rank(30194, 2, 61, "g", 26000, 23730) -- Grimoire of Intercept (Rank 2)
rank(30198, 3, 69, "g", 60000, 23731) -- Grimoire of Intercept (Rank 3)
-- DATA_END
